### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by kholoudfann** [GSG-K3/funny-hooks#8]
Website Design:

- [x] home Component Design

- [x] Categories Component Design

- [x] Joke Component Design

**Comment by Rahaf-96** [comment]
![Desktop - 1](https://user-images.githubusercontent.com/54964739/83641329-0c775700-a5b6-11ea-81f1-39e9ad616eaf.png)

**Comment by Rahaf-96** [comment]
![Desktop - 1 (1)](https://user-images.githubusercontent.com/54964739/83644118-97a61c00-a5b9-11ea-9d2d-4925b70525df.png)
